### ISSUE TITLE
Feature request: allow passing of additional arguments to apt-get update (in dumb_update)

### ISSUE THREAD

**Issue by tfogwill** [xolox/python-apt-mirror-updater#3]
Sometimes it is useful to be able to pass additional arguments to apt-get update (e.g. to handle bad proxies). It would be useful, for code using the API, to be able to pass these to dumb_update.

**Comment by xolox** [comment]
Hi @tfogwill and thanks for the suggestion, it makes sense.

I merged #4 but later decided to change the code so that `dumb_update()` and `smart_update()` accept zero or more positional arguments to pass to `apt-get update` (this feels more elegant to me than passing a list, see the changes in 2cbcaa29a56990c7496cd70da375f2c057572936).

Release 5.0 was just uploaded to PyPI and contains these changes.

**Comment by tfogwill** [comment]
Hi.  That makes sense - thanks for merging and improving.
