### ISSUE TITLE
Incorrect EOL date for Debian Jessie

### ISSUE THREAD

**Issue by xanni** [xolox/python-apt-mirror-updater#5]
Debian Jessie is a LTS supported release, and therefore is not available on archive.debian.org after the 6 June 2018 EOL date in apt-mirror-update.  It will actually move on 6 June 2020 when it goes fully EOL.  apt-mirror-updater currently wrongly switches the sources.list to archive.debian.org which makes Debian Jessie installs break.

**Comment by xolox** [comment]
Hi Andrew and thanks for the feedback. I'm sorry to hear that you were bitten by this bug, I hope the impact wasn't too big. This is fixed in [release 5.1](http://apt-mirror-updater.readthedocs.io/en/latest/changelog.html#release-5-1-2018-06-22) which was published today.

**Explanation:**

Indeed apt-mirror-updater 5.0 didn't contain any specific handling of EOL dates for Debian LTS releases. This is because of the following inconsistency, which I had not expected:

1. The existence of the [Debian LTS project](https://wiki.debian.org/LTS) influences when a Debian stable release is archived to `archive.debian.org` (this is very reasonable, of course).
2. The EOL dates in the [distro-info-data](https://packages.debian.org/distro-info-data) package (more specifically the `/usr/share/distro-info/debian.csv` file) don't reflect the influence of the Debian LTS project.

So I had expected EOL dates of Debian LTS releases to be part of `/usr/share/distro-info/debian.csv` but instead it seems that the data in this file completely ignores the existence of the Debian LTS project...

For a moment I wondered whether I had introduced this inconsistency by using `/usr/share/distro-info/debian.csv` from an Ubuntu system, but no, I just manually downloaded and unpacked [distro-info-data (0.38)](https://packages.debian.org/sid/distro-info-data) from Debian and it lists the same dates.

**Resolution:**

[Release 5.1](http://apt-mirror-updater.readthedocs.io/en/latest/changelog.html#release-5-1-2018-06-22) contains special handling of Debian LTS releases based on the following dates which I took from the [Debian LTS project](https://wiki.debian.org/LTS) page on the Debian wiki:

```python
LTS_RELEASES = {
    'jessie': 1593468000,  # 2020-06-30
    'stretch': 1656540000,  # 2022-06-30
}
```

I don't have a Debian system available to me to test this on, however the `create_chroot()` method is also 100% dependent on the correct selection of a package mirror so that's what I used to test my changes instead:

```python
updater = AptMirrorUpdater(
    distributor_id='debian',
    distribution_codename='jessie',
    architecture='amd64',
)
updater.create_chroot('/tmp/jessie')
```

The code fragment above failed (as expected, based on your bug report) on release 5.0.1 but works fine on release 5.1. I'm going to close this issue now in the assumption that the problem has been properly resolved, but if you run into any further problems feel free to reopen this issue or open a new one.
